### ISSUE TITLE
Twitch video frame is overflowing on mobile devices

### ISSUE THREAD

**Issue by yg** [mutualfun/oneblog#34]
Twitch video frame is overflowing on mobile devices

Reproduced in **Moto G5s Plus**

![photo6174764595177171359](https://user-images.githubusercontent.com/61746440/81463332-847c7800-91d6-11ea-8ba2-0461ec3901bc.jpg)

**Comment by bdougie** [comment]
Fixed in #31 

Can you confirm if its good for you now? @yg

**Comment by yg** [comment]
Yay :tada: 

Fixed and the new UI is awesome @bdougie :clap:
